import type { Metadata } from "next";

import { Fredoka, Nunito } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const isSandbox = process.env.NEXT_PUBLIC_NODE_ENV === 'development';
const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const router = useRouter();
  // const handleMyEvents = () => {
  //   router.push("/my-events");
  // };
  
  // const handleProfile = () => {
  //   router.push("/profile");
  // };

  
  return (
    <html lang="en" className={`${fredoka.className} ${nunito.className}`}>
      <head>
        <Script
          src="https://sdk.minepi.com/pi-sdk.js"
          strategy="beforeInteractive"
        />
        <Script id="pi-sdk" strategy="beforeInteractive">
          {`Pi.init({ version: "2.0", sandbox: ${isSandbox} });`}
        </Script>
        <Script src="https://kit.fontawesome.com/1e3c5331c9.js" strategy="beforeInteractive"/>
      </head>
      <body className={`${fredoka.variable} ${nunito.variable} antialiased`}>
        {children}

        {/* Bottom Navigation */}
        {/* <div className="bottom-nav">
          <button className="nav-item active" onClick={() => router.push("/")}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
              <path
                d="M3 9L12 2L21 9V20C21 20.5304 20.7893 21.0391 20.4142 21.4142C20.0391 21.7893 19.5304 22 19 22H5C4.46957 22 3.96086 21.7893 3.58579 21.4142C3.21071 21.0391 3 20.5304 3 20V9Z"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            <span>Home</span>
          </button>
          <button className="nav-item" onClick={handleMyEvents}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
              <rect
                x="3"
                y="4"
                width="18"
                height="18"
                rx="2"
                ry="2"
                stroke="currentColor"
                strokeWidth="2"
              />
              <line
                x1="16"
                y1="2"
                x2="16"
                y2="6"
                stroke="currentColor"
                strokeWidth="2"
              />
              <line
                x1="8"
                y1="2"
                x2="8"
                y2="6"
                stroke="currentColor"
                strokeWidth="2"
              />
              <line
                x1="3"
                y1="10"
                x2="21"
                y2="10"
                stroke="currentColor"
                strokeWidth="2"
              />
            </svg>
            <span>My Events</span>
          </button>
          <button className="nav-item" onClick={handleProfile}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
              <path
                d="M20 21V19C20 17.9391 19.5786 16.9217 18.8284 16.1716C18.0783 15.4214 17.0609 15 16 15H8C6.93913 15 5.92172 15.4214 5.17157 16.1716C4.42143 16.9217 4 17.9391 4 19V21"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <circle
                cx="12"
                cy="7"
                r="4"
                stroke="currentColor"
                strokeWidth="2"
              />
            </svg>
            <span>Profile</span>
          </button>
        </div> */}
      </body>
    </html>
  );
}
